In [5]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split



In [6]:
df=pd.read_csv("C:\\Users\\Mr\\Desktop\\catdog.csv")

In [7]:
df.head()

height  location  rooms  bath  lounge  bedroom  windows  furnitur  price
0   56.40      80.5      4     2       2        4        5         0     45
1   67.08      29.4      5     3       3        5        4         1     56
2   30.20      30.9      7     6       5        7        5         2     76
3   50.70      56.9      4     3       3        4        3         0     45
4   45.60      78.8      7     6       5        7        6         2     76

In [8]:
x=df.drop(df[["price"]],axis=1)

In [9]:
x

height  location  rooms  bath  lounge  bedroom  windows  furnitur
0   56.40      80.5      4     2       2        4        5         0
1   67.08      29.4      5     3       3        5        4         1
2   30.20      30.9      7     6       5        7        5         2
3   50.70      56.9      4     3       3        4        3         0
4   45.60      78.8      7     6       5        7        6         2
5   33.40      36.9      4     3       2        3        3         0
6   56.70      89.2      3     2       1        2        3         0
7   43.00      34.0      4     3       2        3        4         0
8   50.30      78.9      4     3       2        4        3         0
9   34.00      44.0      4     3       2        3        4         0

In [10]:
y=df[["price"]]
y

price
0     45
1     56
2     76
3     45
4     76
5     43
6     34
7     43
8     44
9     43

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
x_train

height  location  rooms  bath  lounge  bedroom  windows  furnitur
5    33.4      36.9      4     3       2        3        3         0
0    56.4      80.5      4     2       2        4        5         0
7    43.0      34.0      4     3       2        3        4         0
2    30.2      30.9      7     6       5        7        5         2
9    34.0      44.0      4     3       2        3        4         0
4    45.6      78.8      7     6       5        7        6         2
3    50.7      56.9      4     3       3        4        3         0
6    56.7      89.2      3     2       1        2        3         0

In [13]:
y_train

price
5     43
0     45
7     43
2     76
9     43
4     76
3     45
6     34

In [14]:
x_test

height  location  rooms  bath  lounge  bedroom  windows  furnitur
8   50.30      78.9      4     3       2        4        3         0
1   67.08      29.4      5     3       3        5        4         1

In [15]:
x_train.shape

(8, 8)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [17]:
x_train_sc=sc.fit(x_train)
x_test_sc=sc.fit(x_test)

In [18]:
x_train_sc=sc.transform(x_train)
x_test_sc=sc.transform(x_test)


# linear regression model

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
lr=LinearRegression()

In [21]:
lr.fit(x_train,y_train)

LinearRegression()

In [22]:
lr.coef_

array([[ 2.41926820e-15, -1.27675648e-15,  5.58823529e+00,
         1.41176471e+00, -1.41176471e+00,  3.41176471e+00,
        -5.32234846e-15,  1.29411765e+00]])

In [23]:
lr.intercept_

array([9.])

# price of home

In [24]:
x_test.iloc[0, :]


height      50.3
location    78.9
rooms        4.0
bath         3.0
lounge       2.0
bedroom      4.0
windows      3.0
furnitur     0.0
Name: 8, dtype: float64

In [25]:
lr.predict([x_test.iloc[0, :]])

c:\Users\Mr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[46.41176471]])

In [26]:
lr.predict(x_test)

array([[46.41176471],
       [55.29411765]])

In [27]:
y_test

price
8     44
1     56

# accury checking

In [28]:
lr.score(x_test,y_test)

0.9122933487120365

# when our model became overfit we use lesso and ridge model

In [29]:
from sklearn.linear_model import Lasso,Ridge 

In [30]:
rd=Ridge(alpha=0.3)
rd.fit(x_train,y_train)
rd.score(x_test,y_test)

0.8038817542702759

In [31]:
rd.predict(x_test)

array([[44.79450121],
       [52.32722428]])

In [32]:
ls=Lasso(alpha=0.2)
ls.fit(x_train,y_train)
ls.score(x_test,y_test)


0.8185350307538418

In [33]:
ls.predict(x_test)

array([46.19142232, 53.12543116])

In [34]:
y_test

price
8     44
1     56

In [35]:
ls3=Lasso(alpha=5)
ls3.fit(x_train,y_train)
ls3.score(x_test,y_test)


-0.669879169520367

# model evaluation

- root mean sequre

In [36]:
y_predict=lr.predict(x_test)
y_predict

array([[46.41176471],
       [55.29411765]])

- actuall value of y

In [37]:
y_test

price
8     44
1     56

In [38]:
from sklearn.metrics import mean_squared_error

In [39]:
mse=mean_squared_error(y_predict,y_test)
msr=np.sqrt(mse)
print("mean sequre error",mse)
print("mean sequre root",msr)

mean sequre error 3.157439446366686
mean sequre root 1.7769185255285864


In [40]:
from sklearn.metrics import r2_score
r_scor=r2_score(y_test,y_predict)
r_scor

0.9122933487120365

In [41]:
from sklearn.linear_model import  LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [61]:
pn=PolynomialFeatures(degree=2)

In [63]:
pn.fit(x_train)

PolynomialFeatures()

In [64]:
x_train_pn=pn.transform(x_train)
x_test_pn=pn.transform(x_test)

# because of polinomial our data 's feature will be increased

In [65]:
x_train_pn.shape 

(8, 45)

In [66]:
lr=LinearRegression()

In [67]:
lr.fit(x_train_pn,y_train)

LinearRegression()

In [68]:
lr.score(x_test_pn,y_test)

0.661398552773706

In [71]:
lr.predict(x_test_pn[0:1])

array([[45.14092684]])

In [73]:
y_prd_pn=lr.predict(x_test_pn)
y_prd_pn

array([[45.14092684],
       [51.19608596]])

In [74]:
y_test

price
8     44
1     56

In [78]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_prd_pn)
mse
rmse=np.sqrt(mse)


In [79]:
print(mse)
print(rmse)

12.189652100146585
3.491368227521495
